//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ActivityRecords')
export class ActivityRecordsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  recordID: number;

  @Column('integer', { nullable: true })
  userID: number;

  @Column('integer', { nullable: true })
  activityType: number;

  @Column('date', { nullable: true })
  date: Date;

  @Column('real', { nullable: true })
  metric1Value: number;

  @Column('real', { nullable: true })
  metric2Value: number;

  @Column('real', { nullable: true })
  metric3Value: number;

  @Column('real', { nullable: true })
  caloriesBurned: number;
}
