//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('FitnessActivities')
export class FitnessActivitiesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  activityType: string;

  @Column('real', { nullable: true })
  metric1: number;

  @Column('real', { nullable: true })
  metric2: number;

  @Column('real', { nullable: true })
  metric3: number;

  @Column('text', { nullable: true })
  caloriesBurnedFormula: string;
}
