//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Goals')
export class GoalsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  goalID: number;

  @Column('integer', { nullable: true })
  userID: number;

  @Column('integer', { nullable: true })
  targetCalories: number;

  @Column('date', { nullable: true })
  startDate: Date;

  @Column('date', { nullable: true })
  endDate: Date;

  @Column('text', { nullable: true })
  status: string;
}
