//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ActivityRecordsTitle = () => {
  const record = useRecordContext();
  return <span>ActivityRecords {record ? `"${record.recordID}"` : ''}</span>;
};

export const ActivityRecordsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="recordID" />
      <ReferenceField source="userID" reference="Users" />
      <ReferenceField source="activityType" reference="FitnessActivities" />
      <DateField source="date" />
      <NumberField source="metric1Value" />
      <NumberField source="metric2Value" />
      <NumberField source="metric3Value" />
      <NumberField source="caloriesBurned" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ActivityRecordsEdit = () => (
  <Edit title={<ActivityRecordsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="recordID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userID" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="activityType" reference="FitnessActivities" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="metric1Value" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="metric2Value" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="metric3Value" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="caloriesBurned" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ActivityRecordsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="recordID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userID" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="activityType" reference="FitnessActivities" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="metric1Value" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="metric2Value" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="metric3Value" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="caloriesBurned" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput source="userID" label="userID" reference="Users" alwaysOn />,
  <ReferenceInput
    source="activityType"
    label="activityType"
    reference="FitnessActivities"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
];
